# CMake generated Testfile for 
# Source directory: /Users/wpu/Documents/gtsam/gtsam/navigation/tests
# Build directory: /Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testAHRSFactor "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testAHRSFactor")
set_tests_properties(testAHRSFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testAttitudeFactor "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testAttitudeFactor")
set_tests_properties(testAttitudeFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testCombinedImuFactor "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testCombinedImuFactor")
set_tests_properties(testCombinedImuFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testConstantVelocityFactor "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testConstantVelocityFactor")
set_tests_properties(testConstantVelocityFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testImuBias "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testImuBias")
set_tests_properties(testImuBias PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testImuFactor "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testImuFactor")
set_tests_properties(testImuFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testImuFactorSerialization "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testImuFactorSerialization")
set_tests_properties(testImuFactorSerialization PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testManifoldPreintegration "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testManifoldPreintegration")
set_tests_properties(testManifoldPreintegration PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testNavExpressions "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testNavExpressions")
set_tests_properties(testNavExpressions PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testNavState "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testNavState")
set_tests_properties(testNavState PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testPoseVelocityBias "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testPoseVelocityBias")
set_tests_properties(testPoseVelocityBias PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testScenario "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testScenario")
set_tests_properties(testScenario PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testScenarioRunner "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testScenarioRunner")
set_tests_properties(testScenarioRunner PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
add_test(testTangentPreintegration "/Users/wpu/Documents/gtsam/cmake/gtsam/navigation/tests/testTangentPreintegration")
set_tests_properties(testTangentPreintegration PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;27;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam/navigation/tests/CMakeLists.txt;0;")
