# CMake generated Testfile for 
# Source directory: /Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests
# Build directory: /Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(testBatchFixedLagSmoother "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testBatchFixedLagSmoother")
set_tests_properties(testBatchFixedLagSmoother PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testConcurrentBatchFilter "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testConcurrentBatchFilter")
set_tests_properties(testConcurrentBatchFilter PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testConcurrentBatchSmoother "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testConcurrentBatchSmoother")
set_tests_properties(testConcurrentBatchSmoother PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testConcurrentIncrementalFilter "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testConcurrentIncrementalFilter")
set_tests_properties(testConcurrentIncrementalFilter PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testConcurrentIncrementalSmootherDL "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testConcurrentIncrementalSmootherDL")
set_tests_properties(testConcurrentIncrementalSmootherDL PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testConcurrentIncrementalSmootherGN "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testConcurrentIncrementalSmootherGN")
set_tests_properties(testConcurrentIncrementalSmootherGN PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testIncrementalFixedLagSmoother "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testIncrementalFixedLagSmoother")
set_tests_properties(testIncrementalFixedLagSmoother PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testLinearizedFactor "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testLinearizedFactor")
set_tests_properties(testLinearizedFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testNonlinearClusterTree "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testNonlinearClusterTree")
set_tests_properties(testNonlinearClusterTree PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
add_test(testParticleFactor "/Users/wpu/Documents/gtsam/cmake/gtsam_unstable/nonlinear/tests/testParticleFactor")
set_tests_properties(testParticleFactor PROPERTIES  _BACKTRACE_TRIPLES "/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;176;add_test;/Users/wpu/Documents/gtsam/cmake/GtsamTesting.cmake;30;gtsamAddTestsGlob_impl;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;1;gtsamAddTestsGlob;/Users/wpu/Documents/gtsam/gtsam_unstable/nonlinear/tests/CMakeLists.txt;0;")
